version: '3.9'

networks:
  internal:
  external:

services:
  svc-assessor-dc7101v2:
    image: va/abd_vro-assessclaimdc7101v2:latest
    build: ../../../service-python/assessclaimdc7101v2/src/.
    security_opt:
      - no-new-privileges:true
    environment:
      RABBITMQ_PLACEHOLDERS_HOST: rabbitmq-service
      RABBITMQ_PLACEHOLDERS_USERNAME: ${RABBITMQ_PLACEHOLDERS_USERNAME}
      RABBITMQ_PLACEHOLDERS_USERPASSWORD: ${RABBITMQ_PLACEHOLDERS_USERPASSWORD}
      RABBITMQ_PORT: 5672
      RABBITMQ_RETRY_LIMIT: 3
      RABBITMQ_TIMEOUT: 10800
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - internal
    restart: on-failure:5